<a href="https://colab.research.google.com/github/StephenMartinez1/neural-network-challenge-2/blob/main/attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

y_df.head()


Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [4]:
# Create a list of at least 10 column names to use as X data
columns_list = ['Education',
                'Age',
                'DistanceFromHome',
                'JobSatisfaction',
                'OverTime',
                'StockOptionLevel',
                'WorkLifeBalance',
                'YearsAtCompany',
                'YearsSinceLastPromotion',
                'NumCompaniesWorked']

# Create X_df using your selected columns
X_df = attrition_df[columns_list]

# Show the data types for X_df
X_df.dtypes


Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [27]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df,)

In [28]:
# Check the columns of X_train
print(X_train.columns)

Index(['Education', 'Age', 'DistanceFromHome', 'JobSatisfaction', 'OverTime',
       'StockOptionLevel', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsSinceLastPromotion', 'NumCompaniesWorked'],
      dtype='object')


In [31]:
X_train['OverTime'].value_counts()

OverTime
No     806
Yes    296
Name: count, dtype: int64

In [43]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

# Apply LabelEncoder to all object (string) columns in X_train
for col in X_train.select_dtypes(include=['object']):
    X_train[col] = label_encoder.fit_transform(X_train[col])

# Apply LabelEncoder to all object (string) columns in X_test
for col in X_test.select_dtypes(include=['object']):
    X_test[col] = label_encoder.fit_transform(X_test[col])

X_df['OverTime'] = label_encoder.fit_transform(X_df['OverTime'])

print(X_df.dtypes)
X_df.head()

Education                  int64
Age                        int64
DistanceFromHome           int64
JobSatisfaction            int64
OverTime                   int64
StockOptionLevel           int64
WorkLifeBalance            int64
YearsAtCompany             int64
YearsSinceLastPromotion    int64
NumCompaniesWorked         int64
dtype: object


<ipython-input-43-33809547064d>:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_df['OverTime'] = label_encoder.fit_transform(X_df['OverTime'])


Education  Age  DistanceFromHome  JobSatisfaction  OverTime  \
0          2   41                 1                4         1   
1          1   49                 8                2         0   
2          2   37                 2                3         1   
3          4   33                 3                3         1   
4          1   27                 2                2         0   

   StockOptionLevel  WorkLifeBalance  YearsAtCompany  YearsSinceLastPromotion  \
0                 0                1               6                        0   
1                 1                3              10                        1   
2                 0                3               0                        0   
3                 0                3               8                        3   
4                 1                3               2                        2   

   NumCompaniesWorked  
0                   8  
1                   1  
2                   6  
3                   1  
4                   9

In [44]:
# Create a StandardScaler
scaler = StandardScaler()

In [45]:
# Fit the StandardScaler to the training data and testing Data
X_scaler = scaler.fit(X_train)

In [46]:
# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [77]:
X_train_scaled

array([[ 0.06422999, -0.77369818, -0.15564763, ..., -0.48959816,
        -0.37838856,  1.30017027],
       [ 0.06422999,  2.41180122, -0.77441997, ..., -0.16061208,
        -0.6874947 ,  0.90437258],
       [ 1.03383882,  0.32474989, -0.03189317, ..., -0.32510512,
        -0.37838856,  0.1127772 ],
       ...,
       [ 0.06422999,  2.41180122, -0.89817443, ..., -0.32510512,
         0.54892988,  0.1127772 ],
       [ 0.06422999,  0.32474989,  2.07193277, ...,  0.00388096,
         1.47624832, -0.67881818],
       [ 2.00344765,  0.10506028,  2.44319617, ...,  0.49736008,
         2.09446061, -0.67881818]])

In [78]:
X_test_scaled

array([[-0.90537884, -1.2130774 ,  0.21561577, ..., -0.32510512,
         0.23982373, -0.67881818],
       [ 0.06422999, -0.66385337, -0.6506655 , ..., -0.81858424,
        -0.06928241,  2.09176565],
       [ 0.06422999,  0.4345947 , -0.6506655 , ..., -0.6540912 ,
        -0.37838856,  1.30017027],
       ...,
       [ 0.06422999,  0.98381873,  1.08189704, ...,  0.49736008,
        -0.6874947 , -0.28302049],
       [ 0.06422999, -0.44416376,  0.8343881 , ..., -1.14757032,
        -0.6874947 , -0.28302049],
       [ 0.06422999, -0.44416376, -0.52691103, ..., -0.98307728,
        -0.6874947 , -0.67881818]])

In [84]:
# Create a OneHotEncoder for the Department column
ohc = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
y_df_encoded_dept = ohc.fit_transform(y_df[["Department"]])

# Create two new variables by applying the encoder to the training and testing data
y_test_encoded_dept = ohc.transform(y_test[['Department']])
y_train_encoded_dept = ohc.transform(y_train[['Department']])


In [85]:
y_df_encoded_dept

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [81]:
y_test_encoded_dept

array([[0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [82]:
y_train_encoded_dept

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [86]:
# Create a OneHotEncoder for the Attrition column
ohc = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
y_df_encoded_att = ohc.fit_transform(y_df[["Attrition"]])

# Create two new variables by applying the encoder to the training and testing data
y_test_encoded_att = ohc.transform(y_test[['Attrition']])
y_train_encoded_att = ohc.transform(y_train[['Attrition']])


In [87]:
y_df_encoded_att

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [91]:
y_test_encoded_att

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [89]:
y_train_encoded_att

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

## Create, Compile, and Train the Model

In [95]:
# Find the number of columns in the X training data
num_columns_X_train = X_train.shape[1]

# Create the input layer
input_layer = layers.Input(shape=(num_columns_X_train,))

# Create at least two shared layers
shared_layer1 = layers.Dense(64, activation='relu', name='shared_layer1')(input_layer)
shared_layer2 = layers.Dense(32, activation='relu', name='shared_layer2')(shared_layer1)


In [96]:
# Create a branch for Department with a hidden layer and an output layer

# Create the hidden layer
dept_hidden_layer = layers.Dense(units=32, activation='relu', name='dept_hidden_layer')(shared_layer2)

# Create the output layer
dept_output_layer = layers.Dense(units=3, activation='sigmoid', name='dept_output_layer')(dept_hidden_layer)


In [97]:
# Create a branch for Attrition with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden_layer = layers.Dense(units=32, activation='relu', name='attrition_hidden_layer')(shared_layer2)

# Create the output layer
attrition_output_layer = layers.Dense(units=2, activation='sigmoid', name='attrition_output_layer')(attrition_hidden_layer)


In [99]:
# Create the model
model = Model(inputs=input_layer, outputs=[dept_output_layer, attrition_output_layer])


# Compile the model
model.compile(optimizer='adam', loss={'dept_output_layer':'categorical_crossentropy',
                                      'attrition_output_layer':'binary_crossentropy'},
                                metrics={'dept_output_layer':'accuracy','attrition_output_layer':'accuracy'})

# Summarize the model
model.summary()


Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 10)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared_layer1 (Dense)     │ (None, 64)             │            704 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared_layer2 (Dense)     │ (None, 32)             │          2,080 │ shared_layer1[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dept_hidden_layer (Dense) │ (None, 32)             │          1,056 │ shared_layer2[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_hidden_layer    │ (None, 32)             │          1,056 │ shared_layer2[0][0]    │
│ (Dense)                   │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dept_output_layer (Dense) │ (None, 3)              │             99 │ dept_hidden_layer[0][… │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output_layer    │ (None, 2)              │             66 │ attrition_hidden_laye… │
│ (Dense)                   │                        │                │                        │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 5,061 (19.77 KB)

 Trainable params: 5,061 (19.77 KB)

 Non-trainable params: 0 (0.00 B)

In [101]:
# Train the model
model.fit(X_train_scaled, [y_train_encoded_dept, y_train_encoded_att], epochs=10, batch_size=32)

Epoch 1/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - attrition_output_layer_accuracy: 0.7853 - dept_output_layer_accuracy: 0.5119 - loss: 1.6530
Epoch 2/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_layer_accuracy: 0.8231 - dept_output_layer_accuracy: 0.6296 - loss: 1.3201
Epoch 3/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_layer_accuracy: 0.8575 - dept_output_layer_accuracy: 0.6349 - loss: 1.1848
Epoch 4/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_layer_accuracy: 0.8334 - dept_output_layer_accuracy: 0.6274 - loss: 1.2312
Epoch 5/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_layer_accuracy: 0.8393 - dept_output_layer_accuracy: 0.6419 - loss: 1.1842
Epoch 6/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_layer_accuracy: 0.8467 - dept_output_layer_accuracy: 0.6598 - loss: 1.1289
Epoch 7/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_layer_accuracy: 0.8562 - dept_output_layer_accuracy: 0.6421 - loss:

In [111]:
# Evaluate the model with the testing data
results = model.evaluate(X_test_scaled, {'dept_output_layer': y_test_encoded_dept,
                                          'attrition_output_layer': y_test_encoded_att})



12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_layer_accuracy: 0.8622 - dept_output_layer_accuracy: 0.6963 - loss: 1.1207 


In [112]:
# Print the returned values
print(results)

[1.1249971389770508, 0.842391312122345, 0.6820651888847351]


In [113]:
# Print the accuracy for both department and attrition
print('Department predictions accuracy: ', results[1])
print('Attrition predictions accuracy: ', results[2])

Department predictions accuracy:  0.842391312122345
Attrition predictions accuracy:  0.6820651888847351


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. I do not believe that accuracy is the best metric to us on this data.  The data seems to be imbalanced and this impacts the accuracy results. I also believe that other factors play a signifigant part in an emplyoee leaves the company.  Common are due to better offers, family responsiblites, mental health, personality differences with leadership, etc. These are not caputred in the datat set.  If the majorty of employees do not leave, a model could have high accuracy by simply predicting all the employees as non-attrition.

2. The activation i used for output layers was Sigmoid actiation because the classification was binary.

3. Including addtional columns in the X data, increaseing the size of the training dataset, applying weights to class, and adding more layers are a few wayts that this model could be improved.